
export let products = {
    data:[{
        productName: "Yellow color cartoon shirt",
        id: "men Yellow shirt",
        price: "$78",
        discount: "-54%",
        img: "img/products/f1.jpg",
    },
    {
        productName: "White color cartoon shirt",
        id: "men White shirt",
        price: "$90",
        discount: "-24%",
        img: "img/products/f2.jpg",
    },
    {
        productName: "shirt for men",
        id: "men shirt",
        price: "$80",
        discount: "-45%",
        img: "img/products/f3.jpg",
    },
    {
        productName: "full white cartoon shirt",
        id: "men white shirt",
        price: "$78",
        discount: "-35%",
        img: "img/products/f4.jpg",
    },
    {
        productName: "Dark color cartoon shirt",
        id: "men Dark shirt",
        price: "$50",
        discount: "-68%",
        img: "img/products/f5.jpg",
    },
    {
        productName: "Beutiful cartoon shirt for men",
        id: "men shirt",
        price: "$50",
        discount: "-68%",
        img: "img/products/f6.jpg",
    },
    {
        productName: "Beutiful pent for women",
        id: "women pent",
        price: "$50",
        discount: "-68%",
        img: "img/products/f7.jpg",
    },
    {
        productName: "Beutiful sleeve shirt for women",
        id: "women shirt",
        price: "$80",
        discount: "-52%",
        img: "img/products/f8.jpg",
    },
    {
        productName: "White color shirt for men",
        id: "men White shirt",
        price: "$70",
        discount: "-32%",
        img: "img/products/n1.jpg",
    },
    {
        productName: "Grey color shirt for men",
        id: "men Grey shirt",
        price: "$72",
        discount: "-36%",
        img: "img/products/n2.jpg",
    },
    {
        productName: "Light color shirt for men",
        id: "men Light shirt",
        price: "$72",
        discount: "-36%",
        img: "img/products/n3.jpg",
    },
    {
        productName: "Half hand shirt for men",
        id: "Half men shirt",
        price: "$79",
        discount: "-36%",
        img: "img/products/n4.jpg",
    },
    {
        productName: "Full hand shirt for men",
        id: "Full men shirt",
        price: "$78",
        discount: "-36%",
        img: "img/products/n5.jpg",
    },
    {
        productName: "Half pent for men",
        id: "Half men pent",
        price: "$50",
        discount: "-45%",
        img: "img/products/n6.jpg",
    },
    {
        productName: "Full hand shirt for men",
        id: "Full men shirt",
        price: "$59",
        discount: "-36%",
        img: "img/products/n7.jpg",
    },
    {
        productName: "Half hand shirt for men",
        id: "Half men shirt",
        price: "$68",
        discount: "-47%",
        img: "img/products/n8.jpg",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$89",
        discount: "-23%",
        img: "img/t-shirt/tshirt-1.jpg",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$67",
        discount: "-43%",
        img: "img/t-shirt/tshirt-2.webp",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$37",
        discount: "-33%",
        img: "img/t-shirt/tshirt-3.webp",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$37",
        discount: "-33%",
        img: "img/t-shirt/tshirt-4.avif",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$37",
        discount: "-33%",
        img: "img/t-shirt/tshirt-5.avif",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$37",
        discount: "-33%",
        img: "img/t-shirt/tshirt-6.avif",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$37",
        discount: "-33%",
        img: "img/t-shirt/tshirt-7.avif",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$37",
        discount: "-33%",
        img: "img/t-shirt/tshirt-8.avif",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$2.5",
        discount: "-33%",
        img: "img/t-shirt/tshirt-9.avif",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$2.5",
        discount: "-33%",
        img: "img/t-shirt/tshirt-10.webp",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$2.5",
        discount: "-33%",
        img: "img/t-shirt/tshirt-11.webp",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$2.5",
        discount: "-33%",
        img: "img/t-shirt/tshirt-12.webp",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$2.5",
        discount: "-33%",
        img: "img/t-shirt/tshirt-13.webp",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$2.5",
        discount: "-33%",
        img: "img/t-shirt/tshirt-14.avif",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$2.5",
        discount: "-33%",
        img: "img/t-shirt/tshirt-15.avif",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$2.5",
        discount: "-33%",
        img: "img/t-shirt/tshirt-16.avif",
    },
    {
        productName: "Half hand t-shirt for men",
        id: "Half men t-shirt",
        price: "$2.5",
        discount: "-33%",
        img: "img/t-shirt/tshirt-17.avif",
    },
    ]
}

